export const apiRoutes = {
  account: {
    login: '/Account/Login',
  },
  categories: {
    addNewCategory: '/Category/AddNewCategory',
    getAllCategory: '/Category/GetAllCategory',
    editCategory: '/Category/EditCategory',
    deleteCategory: '/Category/DeleteCategory',
    //TODO: wait for endpoint
    getCategoryById: '/Category/GetCategoryById',
  },
  items: {
    addNewItem: '/Item/AddNewItem',
    getAllItems: '/Item/GetAllItems',
    getItemById: '/Item/GetItemById',
    getItemCostById: '/Item/GetItemCostById',
    addItemPrices: '/ItemPrice/AddItemPrices',
    editItem: '/Item/EditItem',
    getItemsPriceForPriceList: '/ItemPrice/GetItemPriceForPriceList',
    deleteItem: '/Item/DeleteItem',
    searchItems: '/Item/SearchItem',
  },
  store: {
    addStore: '/Store/AddStore',
    getItemStoreByItemId: '/ItemStore/GetItemStoreByItemId',
    getAllStores: '/Store/GetAllStores',
    getStoreById: '/Store/GetStoreById',
    getItemPriceByStoreID: '/ItemStore/GetItemPriceByStoreID',
    deleteStore: '/Store/DeleteStore',
    editStore: '/Store/EditStore',
    getAvailableItemsByStoreId: '/ItemStore/GetAvailableItemStoreByStoreID',
    addItemStockForStore: '/ItemStore/AddItemStore',
  },
  priceList: {
    getAllPriceLists: '/PriceList/GetALLPriceLists',
    addNewPriceList: '/PriceList/AddPriceList',
    addItemPrices: '/ItemPrice/AddItemPrices',
    getAllPriceListsForItem: '/ItemPrice/GetItemPriceByItemId',
    updateDescription: '/PriceList/UpdatePriceListDescription'
  },
  provid: {
    addNewProvider: '/Provid/AddNewProvider',
    getALLProvider: '/Provid/GetALLProvider',
    getProviderByID: '/Provid/GetProviderById',
    editProvider: '/Provid/EditProvide',
    deleteProvider: '/Provid/DeleteProvide',
  },
  lookup: {
    ProviderCategory: '/Lookups/ProviderCategory',
    addProviderCategory: '/Lookups/AddProviderCategory',
    Area: '/Lookups/Area',
    addArea: '/Lookups/AddArea',
    Currency: '/Lookups/Currency',
    addCurrency: '/Lookups/AddCurrency',
  },
  dissmissalNotice: {
    addDismissalNotice: '/DismissalNotice/AddDismissalNotice',
    editDismissalNotice: '/DismissalNotice/EditDismissalNotice',
    getAllDismissalNotice: '/DismissalNotice/GetAlldismissalNotice',
    deleteDismissalNotice: '/DismissalNotice/DeleteDismissalNotice',
    getDismissalNoticeById: '/DismissalNotice/GetDismissalNoticeById',
  },
  Transaction: {
    getAllTransactions: '/Transaction/GetALLTransactions',
    getTransactionById: '/Transaction/GetTransactionById',
    editTransaction: '/Transaction/EditItem',
    addTransaction: '/Transaction/AddTransactionList',
    deleteTransaction: '/Transaction/DeleteTransaction',
  },
  PurchaseInvoices: {
    getPurchasesInvoice: '/PurchasesInvoice/GetPurchasesInvoice',
    getPurchasesInvoiceById: '/PurchasesInvoice/GetPurchasesInvoiceById',
    editPurchasesInvoice: '/PurchasesInvoice/EditPurchasesInvoice',
    addPurchasesInvoice: '/PurchasesInvoice/AddPurchasesInvoice',
    deletePurchasesInvoice: '/PurchasesInvoice/DeletePurchasesInvoice',
  },
  stockItemsRequisition: {
    addItemsRequest: '/TransactionPermissions/AddTransactionPermissions',
    editItemRequest: '/TransactionPermissions/EditTransactionPermissions',
    getTransactionsByType: '/Transaction/GetTransactionsByType',
    getTransactionPermissionById: '/TransactionPermissions/GetTransactionPermissionById',
    getAllTransactionsPermission: '/TransactionPermissions/GetAllTransactionPermissions',
  },
};
