export const appRoutes = {
  categories: {
    base: 'categories',
    create: 'create',
    grid: 'grid',
    edit: 'edit',
  },
  items: {
    base: 'items',
    create: 'create',
    addItemPrices: 'add-item-prices',
    grid: 'grid',
    edit: 'edit',
    viewStock: 'view-stock',
  },
  store: {
    base: 'stores',
    addStore: 'add-store',
    grid: 'grid',
    edit: 'edit',
  },
  priceList: {
    base: 'price-list',
    addPriceList: 'add-price-list',
    grid: 'grid',
    priceListItems: 'price-list-items',
    priceListItemsById: 'price-list-items/:id',
  },
  auth: {
    base: 'auth',
    login: 'login',
    register: 'register',
  },
  vendor: {
    base: 'vendor',
    grid: 'grid',
    add: 'add',
    edit: 'edit',
    editById: 'edit/:id',
    view: 'view',
    viewById: 'view/:id',
  },
  dismissalNotice: {
    base: 'dismissal-notice',
    grid: 'grid',
    create: 'create',
    edit: 'edit',
    editById: 'edit/:id',
    disburseOrAddBase: 'disburse-or-add',
    disburseOrAddCreate: 'create',
    disburseOrAddGrid: 'grid',
    disburseOrAddEdit: 'edit',
    disburseOrAddEditById: 'edit/:id',
    // edit: 'edit',
    // view: 'view',
  },
  purchasesInvoice: {
    base: 'purchases-invoice',
    grid: 'grid',
    create: 'create',
    edit: 'edit',
    editById: 'edit/:id',
  },
  stockItemsRequisition: {
    base: 'stock-items-requisition',
    addItemsRequestGrid: 'add-items-request-grid',
    issueItemsRequestGrid: 'issue-items-request-grid',
    addItemsRequest: 'add-items-request',
    issueItemsRequest: 'issue-items-request',

    editAddItemsRequest: 'edit-addition-items-request',
    editIssueItemsRequest: 'edit-issuance-items-request',
  },
};
